---
title: "Run clonealign for sample `r params$id`"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  id: SA609XXX
  pdx: SA609
  clone_prevs: "../data/processed_cnv/clone_prevalence_SA609.csv"
  input_sce: "../data/sces/sce-qc_SA609X3XB01584.rds"
  output_rds: output.rds
  output_cnv: output.cnv
  gex_var_quantile: 0.5
  max_cnv_var: 1
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = FALSE
)


suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(scater)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(TxDb.Hsapiens.UCSC.hg19.knownGene)
  library(org.Hs.eg.db)
  library(GenomicRanges)
  library(matrixStats)
  library(here)
})
```


# Read in data

```{r}
sce <- readRDS(params$input_sce)
```

```{r}
cnv_file <- here("data", "processed_cnv", paste0("cnv_", params$pdx, ".csv"))
cnv <- read_csv(cnv_file)
```

Clone prevalence:

```{r}
df_clone_prev <- read_csv(params$clone_prevs)

timepoint <- sce$timepoint[1]

df_clone_prev <- dplyr::filter(df_clone_prev, time == timepoint)

present_clones <- unique(df_clone_prev$cluster)
```

Select CNV at time point and spread out:

```{r}
cnv <- dplyr::filter(cnv, use_gene) %>%
  dplyr::rename(clone = cluster) %>% 
  dplyr::select(ensembl_gene_id, clone, copy_number) %>% 
  dplyr::filter(clone %in% present_clones) %>% 
  spread(clone, copy_number)
```


# Gene Selection



Now turn into matrix:

```{r}
cnv_mat <- dplyr::select(cnv, -ensembl_gene_id) %>% 
  as.matrix()

rownames(cnv_mat) <- cnv$ensembl_gene_id
```

```{r}
cnv_mat <- cnv_mat[rowVars(cnv_mat) > 0 & rowMins(cnv_mat) > 0 & rowMaxs(cnv_mat) <= 5,]
```


## Expression

Let's subset the SCE to only expressed genes that are in CNV regions: re-QC first

```{r}
rn <- rownames(cnv_mat)
rn <- rn[rn %in% rownames(sce)]

sce <- sce[rn,]

sce <- calculateQCMetrics(sce)

rowData(sce)$var_log_counts <- rowVars(as.matrix(logcounts(sce)))

var_quantile <- quantile(rowData(sce)$var_log_counts, probs = as.numeric(params$gex_var_quantile))

sce <- sce[rowData(sce)$total_counts > 0 & rowData(sce)$var_log_counts > var_quantile,]
```

Remove the usual suspects - genes likely to be affected by tissue dissociation

```{r}
usual_suspects <- grepl("^HSP|^FOS|^JUN|^MALAT1|^UBC", rowData(sce)$Symbol)
sce <- sce[!usual_suspects,]
```


## Take intersect of gene sets

```{r}
common_genes <- intersect(rownames(cnv_mat), rownames(sce))
```

```{r}
cnv_mat <- cnv_mat[common_genes,]
sce <- sce[common_genes,]
```

Final check:

```{r}
stopifnot(all.equal(rownames(cnv_mat), rownames(sce)))
```


# Call clonealign


```{r}
devtools::load_all("/cellassign/clonealign-multinomial/")


ca <- run_clonealign(sce, 
                     cnv_mat,
                     initial_shrinks = c(0, 10),
                     n_repeats = 5,
                     mc_samples = 1,
                     learning_rate = 0.06,
                     max_iter = 600)


```



# Save results

```{r}
saveRDS(ca, params$output_rds)
saveRDS(cnv_mat, params$output_cnv)
```
